concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  COMPILE_MAVEN_OPTS: -Xmx3g -Daether.connector.http.retryHandler.count=5 -Daether.connector.http.connectionMaxTtl=30
  DEFAULT_MAVEN_OPTS: -Xmx4g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
    -Daether.connector.http.retryHandler.count=5 -Daether.connector.http.connectionMaxTtl=30
  MAVEN_BUILD_PROFILES: -P skip-nifi-bin-assembly
  MAVEN_COMMAND: ./mvnw
  MAVEN_COMMAND_WINDOWS: ./mvnw.cmd
  MAVEN_COMPILE_COMMAND: test-compile --show-version --no-snapshot-updates --no-transfer-progress
    --fail-fast -pl -:minifi-integration-tests -pl -:minifi-assembly -pl -:nifi-assembly
    -pl -:nifi-toolkit-assembly -pl -:nifi-registry-assembly -pl -:nifi-registry-toolkit-assembly
    -pl -:nifi-runtime-manifest -pl -:nifi-runtime-manifest-test -pl -:nifi-stateless-assembly
    -pl -:nifi-stateless-system-test-suite -pl -:nifi-system-test-suite -pl -:nifi-nar-provider-assembly
    -pl -:nifi-py4j-integration-tests -pl -:nifi-python-extensions-bundle
  MAVEN_PROJECTS: -pl -minifi/minifi-assembly -pl -minifi/minifi-toolkit/minifi-toolkit-assembly
    -pl -nifi-registry/nifi-registry-assembly -pl -nifi-registry/nifi-registry-toolkit/nifi-registry-toolkit-assembly
    -pl -nifi-stateless/nifi-stateless-assembly -pl -nifi-toolkit/nifi-toolkit-assembly
  MAVEN_VERIFY_COMMAND: verify --show-version --no-snapshot-updates --no-transfer-progress
    --fail-fast -D dir-only
jobs:
  macos-build-jp:
    name: MacOS Zulu JDK 21 JP
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: System Information
      run: 'hostname

        top -l 1 | grep PhysMem

        sysctl machdep.cpu

        df

        '
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Node Modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        path: '~/.npm

          **/node_modules

          '
    - continue-on-error: true
      name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      id: changes
      name: Evaluate Changed Paths
      uses: dorny/paths-filter@v3
      with:
        filters: "frontend:\n  - 'nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/**'\n"
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.COMPILE_MAVEN_OPTS }} -Dfrontend.skipTests=${{ steps.changes.outputs.frontend
          == 'true' && 'false' || 'true' }}
      name: Maven Compile
      run: '${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_COMPILE_COMMAND }}

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.DEFAULT_MAVEN_OPTS }} -DargLine=${env.SUREFIRE_OPTS}
        NIFI_CI_LOCALE: -Duser.language=ja -Duser.country=JP
        SUREFIRE_OPTS: -Duser.language=ja -Duser.country=JP -Duser.region=JP -Duser.timezone=Asia/Tokyo
      name: Maven Verify
      run: ${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_VERIFY_COMMAND }} ${{ env.MAVEN_BUILD_PROFILES
        }} -P python-unit-tests ${{ env.MAVEN_PROJECTS }}
    - continue-on-error: true
      if: failure()
      name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-macos-jp
        path: './**/target/surefire-reports/*.txt

          ./**/target/surefire-reports/*.xml

          '
        retention-days: 3
    - continue-on-error: true
      if: ${{ always() }}
      name: Post Disk Usage
      run: df
    timeout-minutes: 150
  static-analysis:
    name: Static Analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clear Disk Space
      run: 'sudo rm -rf /usr/share/dotnet

        sudo rm -rf /opt/ghc

        sudo rm -rf "/usr/local/share/boost"

        sudo rm -rf /usr/local/lib/android

        '
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Maven Modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-static-analysis-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          '
    - continue-on-error: true
      name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      name: Maven Build
      run: '${{ env.MAVEN_COMMAND }} validate --no-snapshot-updates --no-transfer-progress
        --fail-fast -P contrib-check

        '
    - continue-on-error: true
      name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.COMPILE_MAVEN_OPTS }}
      name: Maven Compile
      run: '${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_COMPILE_COMMAND }}

        '
    - continue-on-error: true
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    timeout-minutes: 120
  ubuntu-build-en:
    name: Ubuntu Corretto JDK 21 EN
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clear Disk Space
      run: 'sudo rm -rf /usr/share/dotnet

        sudo rm -rf /opt/ghc

        sudo rm -rf "/usr/local/share/boost"

        sudo rm -rf /usr/local/lib/android

        '
    - continue-on-error: true
      name: System Information
      run: 'hostname

        cat /proc/cpuinfo

        cat /proc/meminfo

        df

        '
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Node Modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        path: '~/.npm

          **/node_modules

          '
    - continue-on-error: true
      name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: corretto
        java-version: '21'
    - continue-on-error: true
      id: changes
      name: Evaluate Changed Paths
      uses: dorny/paths-filter@v3
      with:
        filters: "frontend:\n  - 'nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/**'\n"
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.COMPILE_MAVEN_OPTS }} -Dfrontend.skipTests=${{ steps.changes.outputs.frontend
          == 'true' && 'false' || 'true' }}
      name: Maven Compile
      run: '${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_COMPILE_COMMAND }}

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.DEFAULT_MAVEN_OPTS }} -Dfrontend.skipTests=${{ steps.changes.outputs.frontend
          == 'true' && 'false' || 'true' }}
      name: Maven Verify
      run: '${{ env.MAVEN_COMMAND }} jacoco:prepare-agent ${{ env.MAVEN_VERIFY_COMMAND
        }} ${{ env.MAVEN_BUILD_PROFILES }} -P report-code-coverage -P python-unit-tests
        ${{ env.MAVEN_PROJECTS }}

        '
    - continue-on-error: true
      if: github.repository_owner == 'apache'
      name: Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./nifi-code-coverage/target/site/jacoco-aggregate/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      if: failure()
      name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-ubuntu-21
        path: './**/target/surefire-reports/*.txt

          ./**/target/surefire-reports/*.xml

          '
        retention-days: 3
    - continue-on-error: true
      if: ${{ always() }}
      name: Post Disk Usage
      run: df
    timeout-minutes: 120
  windows-build:
    name: Windows Zulu JDK 21 FR
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: System Information
      run: 'systeminfo

        df

        '
    - continue-on-error: true
      name: Setup Git
      run: 'git config --global core.autocrlf false

        git config --global core.longpaths true

        '
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache Node Modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        path: '~\AppData\npm-cache

          **\node_modules

          '
    - continue-on-error: true
      name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '21'
    - continue-on-error: true
      id: changes
      name: Evaluate Changed Paths
      uses: dorny/paths-filter@v3
      with:
        filters: "frontend:\n  - 'nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/**'\n"
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.COMPILE_MAVEN_OPTS }} -Dfrontend.skipTests=${{ steps.changes.outputs.frontend
          == 'true' && 'false' || 'true' }}
      name: Maven Compile
      run: '${{ env.MAVEN_COMMAND_WINDOWS }} ${{ env.MAVEN_COMPILE_COMMAND }}

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.DEFAULT_MAVEN_OPTS }} -DargLine=${env.SUREFIRE_OPTS}
        NIFI_CI_LOCALE: -Duser.language=fr -Duser.country=FR
        SUREFIRE_OPTS: -Duser.language=fr -Duser.country=FR -Duser.region=FR -Duser.timezone=Europe/Paris
      name: Maven Verify
      run: ${{ env.MAVEN_COMMAND_WINDOWS }} ${{ env.MAVEN_VERIFY_COMMAND }} ${{ env.MAVEN_BUILD_PROFILES
        }} ${{ env.MAVEN_PROJECTS }}
    - continue-on-error: true
      if: failure()
      name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-windows-fr
        path: './**/target/surefire-reports/*.txt

          ./**/target/surefire-reports/*.xml

          '
        retention-days: 3
    - continue-on-error: true
      if: ${{ always() }}
      name: Post Disk Usage
      run: df
    timeout-minutes: 150
name: ci-workflow
on:
  repository_dispatch:
    types: trigger-ga___ci-workflow.yml
permissions:
  contents: read
  pull-requests: read
  security-events: write
