jobs:
  stale:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: 15
        days-before-stale: 120
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'Automated review is marking this PR as stale due to lack
          of updates in the past four months. This PR will be closed in 15 days if
          the stale label is not removed. This stale label and automated closure does
          not indicate a judgement of the PR, just lack of reviewer bandwidth and
          helps us keep the PR queue more manageable.  If you would like this PR re-opened
          you can do so and a committer can remove the stale label.  Or you can open
          a new PR.  Try to help review other PRs to increase PR review bandwidth
          which in turn helps yours.

          '
name: pull-request-review
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
