concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  DEFAULT_MAVEN_OPTS: -Xmx4g -Duser.language=en -Duser.country=GB -Duser.timezone=UTC
  MAVEN_BUILD_ARGUMENTS: install -D skipTests -am
  MAVEN_COMMAND: ./mvnw -V -nsu -ntp -ff
  MAVEN_PROJECTS: -pl :nifi-python-framework -pl :nifi-python-extension-api -pl :nifi-python-test-extensions
    -pl nifi-system-tests/nifi-system-test-suite -pl nifi-system-tests/nifi-stateless-system-test-suite
  MAVEN_RUN_ARGUMENTS: verify -P integration-tests -D include-python-integration-tests=true
jobs:
  build_and_test:
    env:
      JAVA_DISTRIBUTION: corretto
    name: ${{ matrix.os }} Java ${{ matrix.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: System Information
      run: 'hostname

        if [ "${{ runner.os }}" = "macOS" ]; then top -l 1 | grep PhysMem && sysctl
        machdep.cpu; else cat /proc/cpuinfo && cat /proc/meminfo; fi

        df

        '
    - continue-on-error: true
      if: ${{ runner.os == 'macOS' }}
      name: Use Java distribution Zulu
      run: echo "JAVA_DISTRIBUTION=zulu" >> "$GITHUB_ENV"
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java ${{ env.JAVA_DISTRIBUTION }} ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.DEFAULT_MAVEN_OPTS }}
      name: Build Dependencies
      run: '${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_BUILD_ARGUMENTS }} ${{ env.MAVEN_PROJECTS
        }}

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.DEFAULT_MAVEN_OPTS }}
      name: Run Tests
      run: '${{ env.MAVEN_COMMAND }} ${{ env.MAVEN_RUN_ARGUMENTS }} ${{ env.MAVEN_PROJECTS
        }}

        '
    - continue-on-error: true
      if: failure() || cancelled()
      name: Upload Troubleshooting Logs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.version }}-troubleshooting-logs
        path: 'nifi-system-tests/nifi-system-test-suite/target/failsafe-reports/**/*.txt

          nifi-system-tests/nifi-system-test-suite/target/surefire-reports/**/*.txt

          nifi-system-tests/nifi-system-test-suite/target/troubleshooting/**/*

          '
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-14
        version:
        - 21
    timeout-minutes: 120
name: system-tests
on:
  repository_dispatch:
    types: trigger-ga___system-tests.yml
permissions:
  contents: read
